"""empty message

Revision ID: 07610b567df8
Revises: 6d001748c5e5
Create Date: 2019-02-21 05:48:17.653291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07610b567df8'
down_revision = '6d001748c5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('category')
    # ### end Alembic commands ###
